"""empty message

Revision ID: fb2c4196a76b
Revises: a029a7a86730
Create Date: 2019-12-22 16:37:32.038904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2c4196a76b'
down_revision = 'a029a7a86730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_words', sa.Column('keyword', sa.Text(), nullable=False))
    op.drop_constraint('search_words_keywords_key', 'search_words', type_='unique')
    op.create_unique_constraint(None, 'search_words', ['keyword'])
    op.drop_column('search_words', 'keywords')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_words', sa.Column('keywords', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'search_words', type_='unique')
    op.create_unique_constraint('search_words_keywords_key', 'search_words', ['keywords'])
    op.drop_column('search_words', 'keyword')
    # ### end Alembic commands ###
